drop table dbo.audit_trail
go

CREATE TABLE [dbo].[audit_trail](
	[serial] [int] NOT NULL,
	[date_stamp] [datetime] NOT NULL,
	[type] [char](1) NOT NULL,
	[part] [varchar](25) NOT NULL,
	[quantity] [numeric](20, 6) NOT NULL,
	[remarks] [varchar](10) NOT NULL,
	[price] [numeric](20, 6) NULL,
	[salesman] [varchar](10) NULL,
	[customer] [varchar](10) NULL,
	[vendor] [varchar](10) NULL,
	[po_number] [varchar](30) NULL,
	[operator] [varchar](5) NOT NULL,
	[from_loc] [varchar](10) NULL,
	[to_loc] [varchar](10) NULL,
	[on_hand] [numeric](20, 6) NULL,
	[lot] [varchar](20) NULL,
	[weight] [numeric](20, 6) NULL,
	[status] [char](1) NOT NULL,
	[shipper] [varchar](20) NULL,
	[flag] [char](1) NULL,
	[activity] [varchar](25) NULL,
	[unit] [varchar](2) NULL,
	[workorder] [varchar](10) NULL,
	[std_quantity] [numeric](20, 6) NULL,
	[cost] [numeric](20, 6) NULL,
	[control_number] [varchar](254) NULL,
	[custom1] [varchar](50) NULL,
	[custom2] [varchar](50) NULL,
	[custom3] [varchar](50) NULL,
	[custom4] [varchar](50) NULL,
	[custom5] [varchar](50) NULL,
	[plant] [varchar](10) NULL,
	[invoice_number] [varchar](15) NULL,
	[notes] [varchar](254) NULL,
	[gl_account] [varchar](15) NULL,
	[package_type] [varchar](20) NULL,
	[suffix] [int] NULL,
	[due_date] [datetime] NULL,
	[group_no] [varchar](10) NULL,
	[sales_order] [varchar](15) NULL,
	[release_no] [varchar](15) NULL,
	[dropship_shipper] [int] NULL,
	[std_cost] [numeric](20, 6) NULL,
	[user_defined_status] [varchar](30) NULL,
	[engineering_level] [varchar](10) NULL,
	[posted] [char](1) NULL,
	BF_Number int null,
	[parent_serial] [numeric](10, 0) NULL,
	[origin] [varchar](20) NULL,
	[destination] [varchar](20) NULL,
	[sequence] [int] NULL,
	[object_type] [char](1) NULL,
	[part_name] [varchar](254) NULL,
	[start_date] [datetime] NULL,
	[field1] [varchar](10) NULL,
	[field2] [varchar](10) NULL,
	[show_on_shipper] [char](1) NULL,
	[tare_weight] [numeric](20, 6) NULL,
	[kanban_number] [varchar](6) NULL,
	[dimension_qty_string] [varchar](50) NULL,
	[dim_qty_string_other] [varchar](50) NULL,
	[varying_dimension_code] [numeric](2, 0) NULL,
	invoice varchar(25) null,
	invoice_line smallint null,
	[id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK__audit_tr__3213E83F0F975522] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
go

