CREATE TABLE [dbo].[items]
(
[item] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[item_description] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[changed_date] [datetime] NULL,
[changed_user_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[commodity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[standard_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_selling_uom_to_standard] [decimal] (18, 6) NULL,
[sales_price_uom_to_standard] [decimal] (18, 6) NULL,
[item_type] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_pricing_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_selling_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_analysis] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_ledger_account] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_cost_account] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ledger] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[purchased] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sold] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inventoried] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[security_company] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fulfillment] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[package_length] [decimal] (18, 6) NULL,
[package_height] [decimal] (18, 6) NULL,
[package_width] [decimal] (18, 6) NULL,
[package_gross_weight] [decimal] (18, 6) NULL,
[package_net_weight] [decimal] (18, 6) NULL,
[package_weight_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[package_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[package_dimensions_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[package_uom_to_standard] [decimal] (18, 6) NULL,
[container_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[container_uom_to_package] [decimal] (18, 6) NULL,
[pos_group] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pos_description] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[discount_eligible] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[active_inactive] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[package_label_name] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[container_label_name] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[container_gross_weight] [decimal] (18, 6) NULL,
[container_net_weight] [decimal] (18, 6) NULL,
[container_weight_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[items] ADD CONSTRAINT [pk_items] PRIMARY KEY CLUSTERED  ([item]) ON [PRIMARY]
GO
