CREATE TABLE [dbo].[retirement_plans]
(
[retirement_plan] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[retirement_plan_description] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_stub_description] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_percent_rate_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_amount_rate_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_bt_retirement_plan] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_at_retirement_plan] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_retirement_plan] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[e_cr_ledger_account_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[r_cr_ledger_account_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[r_dr_ledger_account_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employment_types] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eligibility_hire_seniority] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eligibility_years] [smallint] NULL,
[eligibility_months] [smallint] NULL,
[eligibility_days] [smallint] NULL,
[enrollment_month] [smallint] NULL,
[enrollment_day] [smallint] NULL,
[automatic_enrollment] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_percent_rate_event] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_amount_rate_event] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priority] [smallint] NULL,
[arrear] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_percent_rate_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_amount_rate_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ledger] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_sequence] [smallint] NULL,
[changed_date] [datetime] NULL,
[changed_user_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_rate_style] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_rate_style] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[security_unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_breakpoint] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_breakpoint] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[retirement_plan_group] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cost_account_code] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enrollment_style] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[retirement_plans] ADD CONSTRAINT [pk_retirement_plans] PRIMARY KEY CLUSTERED  ([retirement_plan]) ON [PRIMARY]
GO
