CREATE TABLE [dbo].[item_locations]
(
[item] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[inventory_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inventory_uom_to_standard] [decimal] (18, 6) NULL,
[count_cycle] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[receive_ledger_account] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[issue_ledger_account] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[adjust_ledger_account] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[minimum_ave_cost] [decimal] (18, 6) NULL,
[maximum_ave_cost] [decimal] (18, 6) NULL,
[reorder_quantity] [decimal] (18, 6) NULL,
[safety_stock] [decimal] (18, 6) NULL,
[create_po_req] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[on_hand_quantity] [decimal] (18, 6) NULL,
[on_order_quantity] [decimal] (18, 6) NULL,
[sold_quantity] [decimal] (18, 6) NULL,
[reserved_quantity] [decimal] (18, 6) NULL,
[inventory_amount] [decimal] (18, 6) NULL,
[average_cost] [decimal] (18, 6) NULL,
[changed_date] [datetime] NULL,
[changed_user_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[serial_required] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ledger] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[section] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[aisle] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shelf] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[currency] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[receive_ledger_account_credit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[issue_ledger_account_credit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[adjust_ledger_account_credit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_ledger_account_group] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_reorder_rule] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[variance_ledger_account] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[max_reorder_on_hand] [decimal] (18, 6) NULL,
[active_inactive] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[serial_assignment] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[serials_by] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[item_locations] ADD CONSTRAINT [pk_item_locations] PRIMARY KEY CLUSTERED  ([item], [location]) ON [PRIMARY]
GO
