CREATE TABLE [dbo].[ar_headers]
(
[document_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[document] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ship_unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_customer] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_customer] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[send_doc_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contract_po] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[freight_terms] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[price_group] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account_manager] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[document_class] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[terms] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[finance_charge] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[currency] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[intercompany] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[document_comments] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_exempt_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fiscal_year] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ledger] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gl_entry] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[period] [smallint] NULL,
[gl_date] [datetime] NULL,
[ledger_account_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[amount] [decimal] (18, 6) NULL,
[exchanged_amount] [decimal] (18, 6) NULL,
[tax_amount] [decimal] (18, 6) NULL,
[freight_amount] [decimal] (18, 6) NULL,
[applied_amount] [decimal] (18, 6) NULL,
[document_date] [datetime] NULL,
[due_date] [datetime] NULL,
[discount_date] [datetime] NULL,
[last_finance_chg_date] [datetime] NULL,
[changed_date] [datetime] NULL,
[changed_user_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[batch] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exchanged_applied_amount] [decimal] (18, 6) NULL,
[ship_contact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_contact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_order] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_of_lading] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_address_1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_address_2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_address_3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_city] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_state] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_postal_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_address_1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_address_2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_address_3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_city] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_state] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_postal_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_agent] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_terms] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_terms_location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territory] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipper] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_contact_email_address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_contact_email_address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inventory_location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[update_inventory] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc_card] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc_expiration_month] [smallint] NULL,
[cc_expiration_year] [smallint] NULL,
[cc_member] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc_manual] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc_cardpresent] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payment_method] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pos_check_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pos_verification_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[amount_tendered] [decimal] (18, 6) NULL,
[pos_paid] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pos_security_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[program] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[program_event] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[document_source] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lease] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_contact_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_contact_fax_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_contact_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_contact_fax_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc_troutd] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pos_register] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pos_cashier] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc_type] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pos_prepayment] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ar_headers] ADD CONSTRAINT [pk_ar_headers] PRIMARY KEY NONCLUSTERED  ([document_type], [document]) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [ar_headers_batch] ON [dbo].[ar_headers] ([batch]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ar_headers_customer] ON [dbo].[ar_headers] ([bill_customer], [document_type], [document]) ON [PRIMARY]
GO
