CREATE TABLE [dbo].[employees]
(
[employee] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_last_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_first_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[social_security_number] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employment_status] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[office_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email_address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birth_date] [datetime] NULL,
[hire_date] [datetime] NULL,
[termination_date] [datetime] NULL,
[seniority_date] [datetime] NULL,
[currency] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_bank_alias] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bank_account] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[transit_routing_no] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prenotes_required] [smallint] NULL,
[prenotes_given] [smallint] NULL,
[pay_frequency] [int] NULL,
[employment_type] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_picture] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emergency_contact_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[race] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[direct_deposit] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contract_length] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eeoc_pay_type] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dd_account_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[changed_date] [datetime] NULL,
[changed_user_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deceased_date] [datetime] NULL,
[time_card_group] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[time_card_group_sort] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[select_for_calc_thru_date] [datetime] NULL,
[home_email_address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[notification_method] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[send_email_notification_to] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[division] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eir_business_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_faculty_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_position] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[active_inactive] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_ethnic_hispanic] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_race_white] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_race_black] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_race_asian] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_race_indian] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_race_hawaiian] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_non_resident_alien] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tenure_date] [datetime] NULL,
[faculty_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_contract_length] [decimal] (18, 6) NULL,
[dd_foreign] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dd_foreign_bank] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_faculty_contract_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[faculty_contract_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ipeds_2012_contract_length] [decimal] (18, 6) NULL,
[employee_middle_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_cell_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[office_cell_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[security_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[employees] ADD CONSTRAINT [pk_employees] PRIMARY KEY CLUSTERED  ([employee]) ON [PRIMARY]
GO
