CREATE TABLE [dbo].[benefits]
(
[benefit_type] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[benefit_description] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_stub_description] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employment_types] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eligibility_hire_seniority] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eligibility_years] [smallint] NULL,
[eligibility_months] [smallint] NULL,
[eligibility_days] [smallint] NULL,
[enrollment_month] [smallint] NULL,
[enrollment_day] [smallint] NULL,
[automatic_enrollment] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priority] [smallint] NULL,
[arrear] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[number_selections_per_year] [smallint] NULL,
[recalc_as_of_month] [smallint] NULL,
[recalc_as_of_day] [smallint] NULL,
[cr_ledger_account_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dr_ledger_account_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[basis_factor] [decimal] (18, 6) NULL,
[basis_adjustment] [decimal] (18, 6) NULL,
[basis_round] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[basis_round_unit] [smallint] NULL,
[basis_maximum] [decimal] (18, 6) NULL,
[benefit_style] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payer] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ledger] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_sequence] [smallint] NULL,
[changed_date] [datetime] NULL,
[changed_user_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[use_employee_pay_freq] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[number_payments_per_year] [smallint] NULL,
[basis_style] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[security_unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cost_based_on] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rate_id_scheme] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[default_rate_event] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[basis_minimum] [decimal] (18, 6) NULL,
[recalc_age_as_of_month] [smallint] NULL,
[recalc_age_as_of_day] [smallint] NULL,
[recalc_age_update_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cost_account_code] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enrollment_style] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cr_cost_account_code] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[benefits] ADD CONSTRAINT [pk_benefits] PRIMARY KEY CLUSTERED  ([benefit_type]) ON [PRIMARY]
GO
