CREATE TABLE [dbo].[t4_forms]
(
[calendar_year] [smallint] NOT NULL,
[employee] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[business_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t4_sequence] [int] NOT NULL,
[unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[social_insurance_number] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_last_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_first_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_middle_initial] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_address3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_city] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_state] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_postal_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employee_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_address3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_city] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_state] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_postal_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[province_of_employment] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[employment_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cpp_exempt] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ei_exempt] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cpip_exempt] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[amended] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[box14_amount] [decimal] (18, 2) NULL,
[box16_amount] [decimal] (18, 2) NULL,
[box17_amount] [decimal] (18, 2) NULL,
[box18_amount] [decimal] (18, 2) NULL,
[box20_amount] [decimal] (18, 2) NULL,
[box22_amount] [decimal] (18, 2) NULL,
[box24_amount] [decimal] (18, 2) NULL,
[box26_amount] [decimal] (18, 2) NULL,
[box44_amount] [decimal] (18, 2) NULL,
[box46_amount] [decimal] (18, 2) NULL,
[box50_text] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[box52_amount] [decimal] (18, 2) NULL,
[box55_amount] [decimal] (18, 2) NULL,
[box56_amount] [decimal] (18, 2) NULL,
[boxa_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[boxa_amount] [decimal] (18, 2) NULL,
[boxb_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[boxb_amount] [decimal] (18, 2) NULL,
[boxc_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[boxc_amount] [decimal] (18, 2) NULL,
[boxd_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[boxd_amount] [decimal] (18, 2) NULL,
[boxe_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[boxe_amount] [decimal] (18, 2) NULL,
[boxf_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[boxf_amount] [decimal] (18, 2) NULL,
[changed_date] [datetime] NULL,
[changed_user_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[t4_forms] ADD CONSTRAINT [pk_t4_forms] PRIMARY KEY CLUSTERED  ([calendar_year], [employee], [business_number], [t4_sequence], [province_of_employment]) ON [PRIMARY]
GO
