CREATE TABLE [dbo].[so_shippers]
(
[shipper] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ship_customer] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_via] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carrier] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[transport_vessel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[scheduled_ship_date] [datetime] NULL,
[actual_ship_date] [datetime] NULL,
[location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_container] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipper_status] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[booking_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eta_date] [datetime] NULL,
[port_loading] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[port_discharge] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payment_terms] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lcd_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[changed_date] [datetime] NULL,
[changed_user_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[document_note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[document_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[document] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payment_method] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_terms] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_term_location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[freight_terms] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[document_date] [datetime] NULL,
[bill_customer] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_address_1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_address_2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_address_3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_city] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_state] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_postal_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_contact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_contact_email_address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_contact_fax_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_contact_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_address_1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_address_2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_address_3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_city] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_state] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_postal_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_contact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_contact_email_address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_contact_fax_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_contact_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[due_date] [datetime] NULL,
[gl_date] [datetime] NULL,
[fiscal_year] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[batch] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account_manager] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_agent] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[document_class] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ledger_account_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[currency] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[intercompany] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[send_invoice_to] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territory] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipper_note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bol_note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lcd_issuing_bank_address] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lcd_advising_bank_address] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lcd_cover_description] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lcd_amount] [decimal] (18, 6) NULL,
[lcd_currency] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lcd_applicant] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lcd_beneficiary] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lcd_expiration_date] [datetime] NULL,
[ledger] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printed_bol] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gl_entry] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[period] [smallint] NULL,
[price_group] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contract_po] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_exempt_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printed_picklist] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipper_rma_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[update_inventory] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[update_sales_order] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_time] [datetime] NULL,
[document_source] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printed_customs_invoice] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[so_shippers] ADD CONSTRAINT [pk_so_shippers] PRIMARY KEY CLUSTERED  ([shipper], [shipper_rma_flag]) ON [PRIMARY]
GO
