CREATE TABLE [dbo].[req_items]
(
[requisition] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[req_line] [smallint] NOT NULL,
[sort_line] [numeric] (8, 2) NULL,
[line_type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_description] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendors_item] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[freight_carrier] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[expense_analysis] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ledger_account_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[variance_ledger_account] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[purchase_order] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[po_line] [int] NULL,
[quantity_ordered] [numeric] (18, 6) NULL,
[quantity_tolerance] [numeric] (18, 6) NULL,
[purchasing_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[po_pricing_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[purchasing_to_po_pricing_conv] [numeric] (18, 6) NULL,
[price] [numeric] (18, 6) NULL,
[price_tolerance] [numeric] (18, 6) NULL,
[extended_amount] [numeric] (18, 6) NULL,
[required_date] [datetime] NULL,
[shipping_date] [datetime] NULL,
[eta_date] [datetime] NULL,
[location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buy_vendor] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pay_unit] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buyer] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[po_type] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoice_approver] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[changed_date] [datetime] NULL,
[changed_user_id] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[amleadsrcid] [int] NULL,
[package_uom] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[package_uom_to_purchasing] [decimal] (18, 6) NULL,
[sycampusid] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[req_items] ADD CONSTRAINT [pk_req_items] PRIMARY KEY NONCLUSTERED  ([requisition], [req_line]) ON [PRIMARY]
GO
